services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    restart: always
    env_file: ./_config/.env
    depends_on:
      - wordpress
    networks:
      - reverse_proxy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./www/html:/var/www/html
 
  wordpress:
    image: wordpress:php8.3-fpm-alpine
    #image: wordpress:php7.4-fpm-alpine
    container_name: wordpress
    restart: always
    env_file: ./_config/.env
    depends_on:
      - db
    networks:
      - reverse_proxy
    volumes:
      - ./www/html:/var/www/html
      - ./_config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./_config/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf

  db:
    image: yobasystems/alpine-mariadb:10.11.6
    container_name: db
    env_file: ./_config/.env
    restart: always
    networks:
      - reverse_proxy
    volumes:
      - ./www/mysql:/var/lib/mysql
      - ./_config/mariadb_custom.cnf:/etc/my.cnf.d/mariadb_custom.cnf

networks:
  reverse_proxy:
    driver: "bridge"
    name: reverse_proxy